language: php
php:
- '7.2'
services:
- docker
script:
- sudo apt-get install sshpass
deploy:
- provider: script
  script: bash scripts/de.sh staging
  on:
    branch: deploy
after_deploy:
- php scripts/check.php
- export TEST_ACCOUNT_PASSWORD=$TEST_ACCOUNT_PASSWORD
- bash scripts/sc.sh
env:
  global:
  - secure: KU2jJ7ClX/pnfTNBjDTEl99jwXL0yCoFtZCAUtnVO57cCCp7QR5yED+RCGUCpVKo5XCqwxKsMXyHVP0zMv8T0bNbarLc9Cs3A4l43LRGYj1Mnwnb2aVrNx8SBSYTRZbmhdk3hb0XbfLVgw/1ZxGRgHJ7sY7Ay3Lq76hL3A6zEBGemgNB+1/rzbbqmCKO6dc4eqEmp/E+YxBoe8tIhiZ4fL1pw4+xEdXPrtDSDRy6wnJtdyCf/mBtmd+3NoHHxk0iptgKH1IWj1P1ptEJB+PKzM1OQqGAiP0eJIvYnYYFpdYQGzZMN0MwpnADAaZUwAa9KfC4Q7y8iz8OOTOw8q9nuo0bkBWehKU3ReAwY7SQ93yZTkDkYr+x4EobKVbp/qNnCtOyu4ML9Z+jz7gIFWKQmneSEmGArIgbEyvHgARD4L4lvnV9kgPuI5cPDfIdjOaeYahKXUMArUT20h+g3UjVQq36f6J2SGvPs2xHk17kqqxB++7hJFJN3L7CkaBfW/1q3S6GpAN5cCm9+ykPwaX/GrHZvVkHyYvvrQTpWpvuSC0nKC9PZL9oo8oylhdJktPI+J1h3tVBGFs8eDkq9X/H17wmoGd5UFAap0ojMmZ+AFHB041PHBGVXa4/6UK0hpQWCT1cqKQtkXp6TUfu2uS+x7PnkPl9o4UfYYHCy/tusi8=
  - secure: wOzQhDfvSn5QQ5jxeAN4gsHDag8/+yi5y2+I/J5QOOVb3kZNXsyeAPXtki+rUC3Bo9EM2OzGn+dVIDZjs32+tOKPxwb8Pp+faysEJ8IzkmkUtXXtwq8IlBKExt/WDzx/bPEM9a3WrRqJf+cMkrQrDjC4fuH7izsReu47SC/fQrHnyXFJ439bQrBgkr/GabTG0P8Y4C0MJotPTuK/z3bVUGPay5mRyqEulV/vMOCKxvkJrL6o5/UzdTTzgaVD5Z2ILG0ojZyyeifR2YFXbVuH3OjaTjI6P7B9uky97O+J94a/alsl8QkED9DbDl3+s3YoxVpsNJvsBWUDUiqaEpGBY7hJLfAKbPo/kWbklSg5lH9ar85l8fnZBQLYCJ/6ljI/N7GjrdKLkEx9vLm/lAmSAM34vIktyZZC4TlSAOZcIGJkCWxu4fhk1qeXJht98y1V/hMqQspXvO5AAK/HhF0VZRcKBHdRSAMttABxoiDAjWhOEIL5k2T2LK1k5DyRaxgy1LLP437bxzoAonFmx1pHGuFz9PIsHWwJl0FItHAsD2sulXQzfi0NlgzJ3F142OdMQf6JxIhxlX2aQxbMDyiTRyWfBX6wi8lg6W4Yy5SdC+kBlSbw6qC4aNPo+Pk6+TpfD/hmwyEilsYFA10RtGot244yRIRf7cQDvjIuCIMjOBg=
  - REG_TEST_DIR: tests/regression
  - secure: YV9LqX8dj7RCGRp0WdtnrzxnKOS2plj66v+IF7zjv7uqRDb0QNJVefIByHt9z+z1eBPge/CCvoBeKMnqNjW7yIe0BknmN5NNBRjxYBqsNoeMW0kMgakINApqw7HcWcHFNv0KL1CCmn9pauHrefXfI3xKJmLu1nI32X4CgqdAbus4je5bxtuNhvmBfiCXhG8JSu3D62WC/ZeK7mcvAyrm8Fhkjcm+3K6HErvXE/eN3UXW8mEh9WM3pCIWzHncl7SfpY73ZXtBjRmQfBVmRT6eiIZwToDukRvtBBZItesK47Ow7XxxKF7SlraITfzs8YQZF8WfU8lP7r1LxIjA/vvD4poWqpHwuKodTYabPsxsu63MvMd9P/X6xBkNlvXYUu3NrpMLdTBT4K/WSOeQGSkLMDXGX2J5FCj+PuHMNFtSB4jltxKR+6BBfpQVaX/zxPPyfsHHemL8ZVaTA/U2DBSTIKm4/6fzGzcVnLealbLmkVHRed/M8UAp8Vw9abJiJrLlpk4/njCqsdqJ/0pR8uE5x2KU9iTQxoAqFm4mBPD5nksB1b97D05VHVstGTdZGg3451eAzqFm/AyHd9r+TsIzLaic7acVYdSIGqvmtX3H+dXR6LoLU5vsouQmzg3/jj9Uxnmpdb8otqw7KesLQ8rGttljfeWc2yKMK1Hokjs8Pvw=

