language: php
php:
- '7.2'
services:
- docker
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: bash scripts/deploy.sh staging
    only:
      branch: develop
  # deploy master to production
  - provider: script
    script: bash scripts/deploy.sh production
    only:
      branch: master