language: php
php:
- '7.2'
services:
- docker
script:
- echo 'yes'
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: bash scripts/de.sh staging
    on:
      branch: deploy
  # deploy master to production
  - provider: script
    script: bash scripts/de.sh production
    on:
      branch: master
after_deploy:
  - echo $TRAVIS_BRANCH