language: php
php:
- '7.2'
services:
- docker
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: bash scripts/deploy.sh staging
    on:
      branch: deploy
  # deploy master to production
  - provider: script
    script: bash scripts/deploy.sh production
    on:
      branch: master

script:
- echo 'show script'