language: php
php:
- '7.2'
services:
- docker
script:
- export TEST_1=${TEST1}
deploy:
- provider: script
  script: bash scripts/de.sh staging
  on:
    branch: deploy
after_deploy:
- bash $REG_TEST_DIR/scripts/run_regression.sh
env:
  global:
    - REG_TEST_DIR: test/regression
    - REG_TEST_GROUP: sparkle-web